### ISSUE TITLE
CDHInterface web

### ISSUE THREAD

**Issue by irdispsyhonikum** [TMakins/CDHInterface#1]
Hello. 

Which ESP32 dev-boards had you using for this project?

Kind regards
Irdis

**Comment by TMakins** [comment]
Apologies for the late reply - it uses the Arduino "Wire" library to communicate with the I2C module, so it should work with any board that has that library (so pretty much any board that can be programmed using the Arduino IDE).

The pinout of the I2C module (which you can see in the ReadMe for that, [here](https://github.com/TMakins/CDH_I2C_Interface)) matches the NodeMCU pinout, which I believe is the same for all the NodeMCU ESP boards.
